# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v2
    - name: install MQTT broker
      run: sudo apt-get install mosquitto mosquitto-clients libmosquitto-dev
    - name: configure broker
      run: sudo cp mosquitto.conf /etc/mosquitto/conf.d/
    - name: restart broker
      run: sudo systemctl restart mosquitto

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: subscriber log
      run: mosquitto_sub -t '#' -q 2 -F '%I %t %m %l' > /tmp/msg_log.txt &

    - name: Test MQTT sync
      run: python mqtt_sync.py
    - name: Test MQTT async
      run: python mqtt_async.py

    - name: wait the subscriber
      run: while ! wc -l /tmp/msg_log.txt  | grep 200000 ; do sleep 1 ; done

    - uses: actions/upload-artifact@v2
      with:
        name: subscriber_log.txt
        path: /tmp/msg_log.txt